import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { PromptTemplate } from "@langchain/core/prompts";

const getModel = (temp = 0.3) => new ChatGoogleGenerativeAI({
  apiKey: process.env.GOOGLE_API_KEY,
  model: "gemini-flash-latest",
  temperature: temp,
  maxRetries: 1,
});

export const grammarCheck = async (req, res) => {
  try {
    const { text } = req.body;
    if (!text) return res.status(400).json({ error: "Text is required" });
    if (!process.env.GOOGLE_API_KEY) return res.status(401).json({ error: "Google API Key missing" });

    const model = getModel(0.2);
    const template = `You are an expert academic editor. Analyze the following text for:
1. Grammar errors
2. Spelling mistakes
3. Punctuation issues
4. Academic tone improvements
5. Sentence structure suggestions

For each issue found, provide:
- The original text fragment
- The corrected version
- The type of error (grammar/spelling/punctuation/tone/structure)

Then provide an overall quality score from 0-100.

Text:
{text}

Format response as:
## Issues Found
(list each issue)

## Corrected Text
(full corrected version)

## Quality Score: X/100`;

    const prompt = new PromptTemplate({ template, inputVariables: ["text"] });
    const chain = prompt.pipe(model);
    const response = await chain.invoke({ text });
    res.json({ result: response.content });
  } catch (error) {
    console.error("Grammar Check Error:", error.message);
    res.status(500).json({ error: "Failed to check grammar" });
  }
};

export const plagiarismCheck = async (req, res) => {
  try {
    const { text } = req.body;
    if (!text) return res.status(400).json({ error: "Text is required" });
    if (!process.env.GOOGLE_API_KEY) return res.status(401).json({ error: "Google API Key missing" });

    const model = getModel(0.3);
    const template = `You are a plagiarism detection expert. Analyze the following academic text for:
1. Potentially copied or non-original phrases
2. Passages that sound too generic or templated
3. Missing citations for factual claims
4. Paraphrasing that is too close to common source material

For each flagged section:
- Quote the suspicious text
- Explain why it's flagged
- Suggest how to make it more original

Provide an overall originality score from 0-100 (100 = fully original).

Text:
{text}

Format response as:
## Flagged Sections
(list each section)

## Recommendations
(how to improve originality)

## Originality Score: X/100`;

    const prompt = new PromptTemplate({ template, inputVariables: ["text"] });
    const chain = prompt.pipe(model);
    const response = await chain.invoke({ text });
    res.json({ result: response.content });
  } catch (error) {
    console.error("Plagiarism Check Error:", error.message);
    res.status(500).json({ error: "Failed to check plagiarism" });
  }
};

export const aiDetection = async (req, res) => {
  try {
    const { text } = req.body;
    if (!text) return res.status(400).json({ error: "Text is required" });
    if (!process.env.GOOGLE_API_KEY) return res.status(401).json({ error: "Google API Key missing" });

    const model = getModel(0.3);
    const template = `You are an AI content detection expert. Analyze the following text and determine how likely it was generated by AI.

Check for:
1. Overly uniform sentence structure
2. Lack of personal voice or unique perspective
3. Generic academic phrasing patterns
4. Predictable transitions and conclusions
5. Absence of specific examples or data

Provide:
- AI Probability Score (0-100, where 100 = definitely AI-generated)
- Specific sentences that appear AI-generated (quote them)
- Explanation of why each was flagged

Text:
{text}

Format response as:
## AI Detection Score: X/100

## Flagged Sentences
(list each with explanation)

## Overall Assessment
(paragraph explaining the analysis)`;

    const prompt = new PromptTemplate({ template, inputVariables: ["text"] });
    const chain = prompt.pipe(model);
    const response = await chain.invoke({ text });
    res.json({ result: response.content });
  } catch (error) {
    console.error("AI Detection Error:", error.message);
    res.status(500).json({ error: "Failed to detect AI content" });
  }
};

export const humanizeText = async (req, res) => {
  try {
    const { text } = req.body;
    if (!text) return res.status(400).json({ error: "Text is required" });
    if (!process.env.GOOGLE_API_KEY) return res.status(401).json({ error: "Google API Key missing" });

    const model = getModel(0.7);
    const template = `You are an expert academic writer. Rewrite the following text to sound more natural and human-written while maintaining academic quality.

Guidelines:
- Vary sentence length and structure
- Add natural transitions
- Include specific qualifiers and hedging language
- Use active voice where appropriate
- Maintain the same meaning and factual content
- Keep academic standards but add personal scholarly voice

Original Text:
{text}

Provide:
## Humanized Version
(rewritten text)

## Changes Made
(brief list of key changes)`;

    const prompt = new PromptTemplate({ template, inputVariables: ["text"] });
    const chain = prompt.pipe(model);
    const response = await chain.invoke({ text });
    res.json({ result: response.content });
  } catch (error) {
    console.error("Humanize Error:", error.message);
    res.status(500).json({ error: "Failed to humanize text" });
  }
};
